# Site settings
title: "Ryan's Technology Corner"
description: "My personal blogs about technology"
url: "https://rwibawa.github.io"
baseurl: "/"
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: "Ryan Wibawa"
  email: "ryan.wibawa@gmail.com"
  twitter_username: "ryanwibawa"
  facebook_username: "ryan.wibawa"
  github_username:  "rwibawa"
  linkedin_username:  "ryan-wibawa-8318555"

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
